const fs = require('fs-extra');
const path = require('path');
const { randomBytes } = require('crypto');

module.exports = (api) => {
  /**
   * Backs up all necessary app data stored for Verus Desktop
   */
  api.backupAppData = async (backupName) => {
    if (typeof backupName !== "string" || !/^[0-9a-zA-Z_-]+$/.test(backupName)) {
      throw new Error(`Backup data name (${backupName}) cannot include any of the following: ./\\*~`)
    }

    try {
      await fs.access(api.paths.agamaDir, fs.constants.R_OK);
    } catch (e) {
      throw new Error(`Verus Desktop data directory is not readable: ${e.message}`);
    }

    try {
      const backupPath = `${api.paths.backupDir}/${backupName}`

      if (await fs.pathExists(backupPath)) {
        throw new Error(`Backup at ${backupPath} already exists!`)
      }

      const partialBackup = path.join(
        api.paths.backupDir,
        `.${backupName}.partial-${process.pid}-${randomBytes(8).toString("hex")}`
      );
      try {
        await fs.copy(api.paths.agamaDir, partialBackup, {
          errorOnExist: true,
          overwrite: false,
        });
        await fs.chmod(partialBackup, 0o700);
        const secretBackup = path.join(partialBackup, "builtinsecret.json");
        if (await fs.pathExists(secretBackup)) await fs.chmod(secretBackup, 0o600);
        await fs.rename(partialBackup, backupPath);
      } catch (error) {
        // This path is uniquely generated by this invocation and is never a
        // live or previously completed backup.
        try { await fs.remove(partialBackup); } catch (cleanupError) {}
        throw error;
      }

      api.log(
        `appdata backup created at ${backupPath}`,
        "backup"
      );
      return
    } catch (e) {
      api.log(e, 'backup');
      throw e
    }
  };

  api.setPost('/backup_appdata', async (req, res, next) => {
    const { dirName } = req.body
   
    try {
      const retObj = {
        msg: 'success',
        result: await api.backupAppData(dirName),
      };

      res.send(JSON.stringify(retObj));
    } catch (e) {
      const retObj = {
        msg: 'error',
        result: e.message,
      };

      res.send(JSON.stringify(retObj));
    }
  });

  return api;
};
